services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - client-server-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://root:root@mongo:27017/data@?authSource=admin
    networks:
      - client-server-network
      - server-database-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # volumes:
    #   - ./database:/data/db
    #   - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - server-database-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=data

networks:
  client-server-network:
    driver: bridge
  server-database-network:
    driver: bridge
